name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main # Trigger workflow on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: read       # Read repository contents
  pages: write         # Enable deployment to GitHub Pages
  id-token: write      # Required for authentication during deployment

jobs:
  # Step 1: Build the Next.js Site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4 # Check out the latest code in the repository

      - name: Set Environment Variables
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use Node.js version 20
          cache: npm         # Cache dependencies for faster builds

      - name: Install Project Dependencies
        run: npm install     # Install dependencies defined in package.json

      - name: Build and Export Next.js Site
        run: |
          npm run build      # Build the project
          npm run export     # Export static files to the ./out directory

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out        # Upload the static files from the ./out directory

  # Step 2: Deploy the Site to GitHub Pages
  deploy:
    environment:
      name: github-pages      # Specify the deployment environment
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build              # Run after the build job is complete
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploy uploaded artifacts to GitHub Pages
